# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: OwnVideo Sample Site
description: My name is John Doe, and these are my videos.
author:
  name: John Doe
  url: http://example.com/

url: http://localhost:4000/ # Absolute path
video-baseurl: http://localhost:4000/video/ # Absolute path where video folder resides (can be a folder on a CDN)

# ----------------------- #
#    Optional Features    #
# ----------------------- #

# If a url is provided, a subscribe button under the video will lead to it (hint: use something like a MailChimp subscribe page!)
subscribe-button-url: http://example.com/ 

# If a Disqus shortname is provided here, a Disqus comment thread will be created for each video.
disqus-shortname: 

# If provided, Google Analytics tracking code will be added to every page on your site.
# Your analytics id should be in the format "UA-XXXXXXXX-X".
google-analytics-id: 

# How many videos to display in the sidebar
up-next-count: 5

# ----------------------- #
#     Static Configs      #
# ----------------------- #

permalink: /watch/:title/
exclude: [source_video]

category_archive:
    slugify: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: watch
